services:
  - type: web
    name: telegram-bot-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: WEBHOOK_BASE
        sync: false

  - type: worker
    name: trade-signal-scanner
    env: python
    plan: free
    numInstances: 1
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python scanner_main.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PUMP_THRESHOLD
        value: "0.07"
      - key: RSI_MIN
        value: "70"
      - key: SCAN_INTERVAL
        value: "60"
      - key: SYMBOL_REFRESH_SEC
        value: "86400"
      - key: QUOTE_FILTER
        value: "USDT"
      - key: MAX_CONCURRENCY
        value: "8"
      - key: COOLDOWN_SEC
        value: "900"
      - key: PYTHON_VERSION
        value: "3.11.9"
