
services:
  - type: web
    name: telegram-bot-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: WEBHOOK_BASE
        sync: false
