services:
  - type: web
    name: telegram-bot-webhook
    env: python
    plan: free
    buildCommand: "pip install -U pip wheel setuptools && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: WEBHOOK_BASE
        sync: false
      - key: PORT
        value: "10000"

      # --- настройки сканера (раз уж он теперь внутри web) ---
      - key: UNIVERSE_REFRESH_MODE
        value: seed
      - key: SIGNAL_SOURCE
        value: spot
      - key: REQUIRE_SPOT_USDT
        value: "true"
      - key: PUMP_THRESHOLD
        value: "0.025"
      - key: RSI_MIN
        value: "60"
      - key: COOLDOWN_SEC
        value: "120"
      - key: ENTRY_MODE
        value: break1m
      - key: ALIASES
        value: "MATICUSDT=POLUSDT;FTMUSDT=REMOVE"
